{
 "title": "Oxidized",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Model",
    "query": {
     "query": "label_values(oxidized_device_status,model)"
    }
   },
   {
    "name": "Group",
    "query": {
     "query": "label_values(oxidized_device_status,group)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "label_values(oxidized_device_status{group=~\"$Group\", model=~\"$Model\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status Oxidized",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oxidized_status" }
   ]
  },
  {
   "title": "Devices backed up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"full_name\", oxidized_device_status{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Config lines backed up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(oxidized_device_config_lines{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of all backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(oxidized_device_config_size{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed or not tried yet",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oxidized_device_status{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"} == 0 or oxidized_device_status{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"} == 1",
     "legendFormat": "{{ full_name }} {{ model }}"
    }
   ]
  },
  {
   "title": "Duration of backup",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "oxidized_device_last_backup_time{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"}",
     "legendFormat": "{{ full_name }} - {{ model }}"
    }
   ]
  },
  {
   "title": "Device backups",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oxidized_device_status{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"}",
     "legendFormat": "{{ full_name }} {{ model }}"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Devices" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (group)(oxidized_device_status{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Models",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Devices" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (model)(oxidized_device_status{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Number of lines by model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Lines" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model)(oxidized_device_config_lines{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Average number of lines by model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Lines" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (model)(oxidized_device_config_lines{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Config size by model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model)(oxidized_device_config_size{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Average config size by model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (model)(oxidized_device_config_size{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"})",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Number of config lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Lines" } },
   "targets": [
    {
     "expr": "oxidized_device_config_lines{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"}",
     "legendFormat": "{{ full_name }}"
    }
   ]
  },
  {
   "title": "Config size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "oxidized_device_config_size{model=~\"$Model\", group=~\"$Group\", name=~\"$Device\"}",
     "legendFormat": "{{ full_name }}"
    }
   ]
  },
  {
   "title": "Time taken to collect metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "oxidized_exporter_collect_duration",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}